---
- name: deployment
  hosts: all
  become: True
  vars:
    nexus_url: http://65.0.54.66:8081/repository
    repository_type: java-maven-app-releases
    group_id: com%2Fmycompany%2Fapp
    artifact_id: hello-world-war
    version: 1.0.0
    build_number: "{{build_number}}"
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "{{nexus_url}}/{{repository_type}}/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war"
      dest: /home/ec2-user/tomcat
      username: admin
      password: admin

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/tomcat/{{group_id}}%2F{{artifact_id}}%2F{{version}}-{{build_number}}%2F{{artifact_id}}-{{version}}-{{ build_number}}.war /home/ec2-user/tomcat/{{artifact_id}}-{{version}}-{{ build_number}}.war

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/tomcat/{{artifact_id}}-{{version}}-{{ build_number}}.war /home/ec2-user/tomcat/apache-tomcat-9.0.72/webapps/{{artifact_id}}-{{version}}-{{ build_number}}.war

  - name: find the process
    ansible.builtin.shell: "rm -rf cp /home/ec2-user/tomcat/{{artifact_id}}-{{version}}-{{ build_number}}.war"